# Generated by Django 5.0.3 on 2024-03-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_social_login',
            field=models.BooleanField(default=False),
        ),
    ]
