# Generated by Django 5.0.3 on 2024-03-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_bio_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='Hey there! i am using chatbox'),
        ),
    ]
