# Generated by Django 5.0.3 on 2024-03-12 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room_id', models.CharField(max_length=100, unique=True)),
                ('chat_type', models.CharField(choices=[('one_to_one', 'One to One'), ('group', 'Group')], default='one_to_one', max_length=20)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('members', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
