# Generated by Django 4.0.1 on 2024-04-16 12:56

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_document_chatmessage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='duration_seconds',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.user_media_path),
        ),
    ]
