# Generated by Django 4.0.1 on 2024-04-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_aimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
