# Generated by Django 4.0.1 on 2024-04-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_userconnectedstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chat_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
