name: chat_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  permission_handler: ^11.3.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  http: ^1.2.1
  flutter_otp_text_field: ^1.1.1
  flutter_spinkit: ^5.2.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Caros-Bold
      fonts:
        - asset: assets/fonts/caros-bold-fsp.otf
    - family: Caros-Medium
      fonts:
        - asset: assets/fonts/caros-medium-fsp.otf
    - family: Caros-Regular
      fonts:
        - asset: assets/fonts/caros-regular-fsp.otf
    - family: CircularStd-Bold
      fonts:
        - asset: assets/fonts/CircularStd-Bold.otf
    - family: CircularStd-Medium
      fonts:
        - asset: assets/fonts/CircularStd-Medium.otf
    - family: CircularStd-Book
      fonts:
        - asset: assets/fonts/CircularStd-Book.otf
    - family: CircularStd-MediumItalic
      fonts:
        - asset: assets/fonts/CircularStd-MediumItalic.otf
    - family: SfBold
      fonts:
        - asset: assets/fonts/sfBold.otf
    - family: SFLight
      fonts:
        - asset: assets/fonts/sfLight.otf
    - family: SFMedium
      fonts:
        - asset: assets/fonts/sfMedium.otf
    - family: SFRegular
      fonts:
        - asset: assets/fonts/sfRegular.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700